<a href="https://colab.research.google.com/github/MobiTecno/PythonClub/blob/master/neuronio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
entradas =[-1,7,5]
pesos =[0.8,0.1,0]

def soma(e,p):
  s =0
  for i in range(3):
    #print(entradas[i])
    #print(pesos[i])
    s+=e[i]*p[i]
  return s
s=soma(entradas,pesos)

def funcaoativacao(soma):
  if(soma>=1):
    return 1
  return 0

r =funcaoativacao(s)

print(r)

0


In [0]:
import numpy as np

entradas =np.array([1,7,5])
pesos =np.array([0.8,0.1,0])

def soma(e,p):
 
 return e.dot(p)
s=soma(entradas,pesos)

def funcaoativacao(soma):
  if(soma>=1):
    return 1
  return 0

r =funcaoativacao(s)

print(r)


1


In [0]:
import numpy as np

#entradas =np.array([[0,0],[0,1],[1,0],[1,1]])
#saidas =np.array([0,0,0,1])
#entradas =np.array([[0,0],[0,1],[1,0],[1,1]])
#saidas =np.array([0,1,1,1])
entradas =np.array([[0,0],[0,1],[1,0],[1,1]])
saidas =np.array([0,1,1,0])
pesos = np.array([0.0,0.0])
taxaAprendizagem =0.1

def ativacao(soma):
  if(soma>=1):
    return 1
  return 0

def calculaSaida(registro):
  s = registro.dot(pesos)
  return ativacao(s)

def treinar():
  erroTotal =1
  while(erroTotal !=0):
    erroTotal =0
    for i in range(len(saidas)):
      saidaCalculada =calculaSaida(np.asarray(entradas[i]))
      erro =abs(saidas[i]-saidaCalculada)
      erroTotal+=erro
      for j in range(len(pesos)):
        pesos[j] =pesos[j]+(taxaAprendizagem*entradas[i][j]*erro)
        print('Peso atualizado:'+str(pesos[j]))
    print('Total de erros'+str(erroTotal))
treinar()
print('Rede treinada')
print(calculaSaida(entradas[0]))
print(calculaSaida(entradas[1]))
print(calculaSaida(entradas[2]))
print(calculaSaida(entradas[3]))



Streaming output truncated to the last 5000 lines.
Peso atualizado:4289.499999998074
Peso atualizado:4289.499999998074
Peso atualizado:4289.499999998074
Peso atualizado:4289.499999998074
Peso atualizado:4289.599999998074
Peso atualizado:4289.599999998074
Total de erros1
Peso atualizado:4289.599999998074
Peso atualizado:4289.599999998074
Peso atualizado:4289.599999998074
Peso atualizado:4289.599999998074
Peso atualizado:4289.599999998074
Peso atualizado:4289.599999998074
Peso atualizado:4289.699999998074
Peso atualizado:4289.699999998074
Total de erros1
Peso atualizado:4289.699999998074
Peso atualizado:4289.699999998074
Peso atualizado:4289.699999998074
Peso atualizado:4289.699999998074
Peso atualizado:4289.699999998074
Peso atualizado:4289.699999998074
Peso atualizado:4289.799999998075
Peso atualizado:4289.799999998075
Total de erros1
Peso atualizado:4289.799999998075
Peso atualizado:4289.799999998075
Peso atualizado:4289.799999998075
Peso atualizado:4289.799999998075
Peso atualizado:4

In [0]:
# rede multi-neural apartir daqui

import numpy as np

def sigmoid(soma):
  return 1/(1+np.exp(-soma)) #----------> função sigmoid,para raizes não lineares

entradas =np.array([[0,0],[0,1],[1,0],[1,1]])
saidas =np.array([[0],[1],[1],[0]])

pesos0 =np.array([[-0.424,-0.740,-0.961],
                  [0.358,-0.577,-0.469]]) #-------->pesos da entrada 
pesos1 =np.array([[-0.017],[-0.893],[0.148]])#-------> pesos da camada oculta

epocas =100

for i in range(epocas):
  camadaEntrada = entradas
  somaSinapse =np.dot(camadaEntrada, pesos0)
  camadaOculta =sigmoid(somaSinapse)

  print(camadaOculta)

[[0.5        0.5        0.5       ]
 [0.5885562  0.35962319 0.38485296]
 [0.39555998 0.32300414 0.27667802]
 [0.48350599 0.21131785 0.19309868]]
[[0.5        0.5        0.5       ]
 [0.5885562  0.35962319 0.38485296]
 [0.39555998 0.32300414 0.27667802]
 [0.48350599 0.21131785 0.19309868]]
[[0.5        0.5        0.5       ]
 [0.5885562  0.35962319 0.38485296]
 [0.39555998 0.32300414 0.27667802]
 [0.48350599 0.21131785 0.19309868]]
[[0.5        0.5        0.5       ]
 [0.5885562  0.35962319 0.38485296]
 [0.39555998 0.32300414 0.27667802]
 [0.48350599 0.21131785 0.19309868]]
[[0.5        0.5        0.5       ]
 [0.5885562  0.35962319 0.38485296]
 [0.39555998 0.32300414 0.27667802]
 [0.48350599 0.21131785 0.19309868]]
[[0.5        0.5        0.5       ]
 [0.5885562  0.35962319 0.38485296]
 [0.39555998 0.32300414 0.27667802]
 [0.48350599 0.21131785 0.19309868]]
[[0.5        0.5        0.5       ]
 [0.5885562  0.35962319 0.38485296]
 [0.39555998 0.32300414 0.27667802]
 [0.48350599 0.2113178